services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recetas
